name = "lapce-pyright"
version = "0.1.0"
author = "abreumatheus"
display-name = "Python (pyright)"
description = "Pyright LSP for the Lapce editor."
wasm = "bin/lapce-pyright.wasm"
icon = "assets/icon.png"

[activation]
language = ["python"]
workspace-contains = ["*/*.py"]
